version: '3'

services:
  nginx:
    image: nginx:1.21.6
    container_name: nginx
    ports:
      - "9080:80"
      - "9443:443"
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./nginx/html:/usr/share/nginx/html
    restart: always
  nacos:
    image: nacos/nacos-server:v2.2.2-slim
    container_name: nacos
    env_file:
      - env/nacos-standalone-mysql.env
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    restart: always
    depends_on:
      - mysql
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    depends_on:
      - grafana
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_ROLE: 'Admin'
  mysql:
    image: mysql:8.0.35
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: 'root'
#    volumes:
#      - ./volumes/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
  rocketmq:
    image: king019/rocketmq
    container_name: rocketmq
    environment:
      JAVA_OPT_EXT: '-Xms128m -Xmx128m -Xmn64m -XX:MetaspaceSize=32m -XX:MaxMetaspaceSize=32m'
    env_file:
      - ./env/service-common.env
    ports:
      - "9876:9876"
      - "10911:10911"
    restart: always
    command:
      - /bin/sh
      - -c
      - echo brokerIP1=$(hostname -i) > opt/soft/rocketmq/conf/broker.properties && /docker.sh
  rocketmq-console:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: rocketmq-console
    ports:
      - "19876:8080"
    environment:
      JAVA_OPTS: -Drocketmq.config.namesrvAddr=rocketmq:9876 -Drocketmq.config.isVIPChannel=false
    depends_on:
      - rocketmq
  redis:
    container_name: redis
    image: redis:6.2
    restart: always
    ports:
      - "6379:6379"
    environment:
      LANG: C.UTF-8
      TZ: "Asia/Shanghai"
    volumes:
      - ./volumes/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command:
      - 'redis-server'
      - '/usr/local/etc/redis/redis.conf'
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2024-01-13T07-53-03Z-cpuv1
    restart: always
    ports:
      - "9000:9000"
      - "9100:9100"
    environment:
      LANG: C.UTF-8
      TZ: "Asia/Shanghai"
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123456
#    volumes:
#      - ./volumes/minio/data:/home/data
#      - ./volumes/minio/config:/root/.minio
    command: server /home/data --console-address ":9100"
  canal:
    image: canal/canal-server:v1.1.7
#    environment:
#      canal.destinations: example
#      canal.instance.master.address: mysql:3306
    ports:
      - "11110:11110"
      - "11111:11111"
      - "11112:11112"
#      - "9100:9100"
  es-01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.7
    container_name: es-01
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
#    volumes:
#      - ./volumes/elasticsearch/data:/usr/share/elasticsearch/data
#      - ./volumes/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  kib-01:
    image: docker.elastic.co/kibana/kibana:7.17.7
    container_name: kib-01
    volumes:
      - ./volumes/kibana/config:/usr/share/kibana/config
    ports:
      - "9400:5601"
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://es-01:9200
  gateway:
    container_name: ark-center-gateway
    image: ark-center-gateway:1.0.0
    restart: always
    ports:
      - "8082:8082"
    env_file:
      - ./env/service-common.env
    depends_on:
      - nacos
      - redis
  oss:
    container_name: ark-center-oss
    image: ark-center-oss:1.0.0
    restart: always
    ports:
      - "8084:8084"
    env_file:
      - ./env/service-common.env
    depends_on:
      - nacos
      - redis
      - minio
  iam:
    container_name: ark-center-iam
    image: ark-center-iam:1.0.0
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - "./iam:/app/logs/iam"
    env_file:
      - ./env/service-common.env
    depends_on:
      - nacos
      - redis
      - rocketmq
  auth:
    container_name: ark-center-auth
    image: ark-center-auth:1.0.0
    restart: always
    ports:
      - "8089:8089"
    volumes:
      - "./auth:/app/logs/auth"
    env_file:
      - ./env/service-common.env
    depends_on:
      - nacos
      - redis
      - iam
      - rocketmq
  trade:
    container_name: ark-center-trade
    image: ark-center-trade:1.0.0
    restart: always
    ports:
      - "8085:8085"
    env_file:
      - ./env/service-common.env
    depends_on:
      - nacos
      - redis
      - rocketmq
  pay:
    container_name: ark-center-pay
    image: ark-center-pay:1.0.0
    restart: always
    ports:
      - "8086:8086"
    env_file:
      - ./env/service-common.env
    depends_on:
      - nacos
      - redis
      - rocketmq
#  eop:
#    container_name: ark-center-eop
#    image: ark-center-eop:1.0.0
#    restart: always
#    ports:
#      - "8081:8081"
#    env_file:
#      - ./env/service-common.env
#    depends_on:
#      - nacos
#      - redis
  product:
    container_name: ark-center-product
    image: ark-center-product:1.0.0
    restart: always
    ports:
      - "8083:8083"
    env_file:
      - ./env/service-common.env
    depends_on:
      - nacos
      - redis
      - es-01
      - oss
    command:
      - 'tail -f logs/product/product.log'