apiVersion: v1
kind: ConfigMap
metadata:
  name: ark-configmap
  namespace: ark-dev
data:
#  NACOS_DISCOVERY_IP: 192.168.31.21
  NACOS_DISCOVERY_SERVER_ADDR: nacos.ark-dev.svc:8848
  NACOS_CONFIG_SERVER_ADDR: nacos.ark-dev.svc:8848
  SYS_OPT: "-DSpring.profiles.active=dev"
  LANG: C.UTF-8
  TZ: "Asia/Shanghai"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ark-center-iam
  namespace: ark-dev
  labels:
    app: ark-center-iam
spec:
  replicas: 1
  template:
    metadata:
      name: ark-center-iam
      labels:
        app: ark-center-iam
    spec:
      containers:
        - name: ark-center-iam
          image: ark-center-iam:v1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: ark-configmap
      restartPolicy: Always
  selector:
    matchLabels:
      app: ark-center-iam
---
apiVersion: v1
kind: Service
metadata:
  name: ark-center-iam
spec:
  selector:
    app: ark-center-iam
  ports:
    - port: 8080  
  type: NodePort