apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: ark-dev
  labels:
    app: minio
spec:
  replicas: 1
  template:
    metadata:
      name: minio
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio
          imagePullPolicy: IfNotPresent
          env:
            - name: LANG
              value: C.UTF-8
            - name: TZ
              value: "Asia/Shanghai"
            - name: MINIO_ROOT_USER
              value: admin
            - name: MINIO_ROOT_PASSWORD
              value: admin123456
#          command:
#            - server /data --console-address ":9100"
          command:
            - /bin/sh
            - -c
            - minio server /data --console-address ":9100"
      restartPolicy: Always
  selector:
    matchLabels:
      app: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: ark-dev
spec:
  selector:
    app: minio
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: tcp
    - port: 9100
      targetPort: 9100
      protocol: TCP
      name: tcp2
  type: NodePort
---