apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-configmap
  namespace: ark-dev
data:
  PREFER_HOST_MODE: "hostname"
  MODE: "standalone"
  SPRING_DATASOURCE_PLATFORM: "mysql"
  MYSQL_SERVICE_HOST: "gz-cynosdbmysql-grp-irl7x9ar.sql.tencentcdb.com"
  MYSQL_SERVICE_PORT: "20716"
  MYSQL_SERVICE_DB_NAME: "nacos_config"
  MYSQL_SERVICE_USER: "kt_cloud8888"
  MYSQL_SERVICE_PASSWORD: "Kt.cloud1234!@#$"
  MYSQL_SERVICE_DB_PARAM: "characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos
  namespace: ark-dev
  labels:
    app: nacos
spec:
  replicas: 1
  template:
    metadata:
      name: nacos
      labels:
        app: nacos
    spec:
      containers:
        - name: nacos
#          ports:
#            - containerPort: 8848
#              name: ui-port
#            - containerPort: 9848
#              name: tcp-port
          image: nacos/nacos-server:v2.1.1-slim
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: nacos-configmap
      restartPolicy: Always
  selector:
    matchLabels:
      app: nacos
---
apiVersion: v1
kind: Service
metadata:
  name: nacos
  namespace: ark-dev
spec:
  selector:
    app: nacos
  ports:
    - port: 8848
      targetPort: 8848
      protocol: TCP
      name: ui
    - port: 9848
      targetPort: 9848
      protocol: TCP
      name: grpc
  type: NodePort
---