apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: ark-dev
  labels:
    app: redis
spec:
  replicas: 1
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: nacos-configmap
      restartPolicy: Always
  selector:
    matchLabels:
      app: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: ark-dev
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: tcp
  type: NodePort
---