apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketmq
  namespace: ark-dev
  labels:
    app: rocketmq
spec:
  replicas: 1
  template:
    metadata:
      name: rocketmq
      labels:
        app: rocketmq
    spec:
      containers:
        - name: rocketmq
          image: king019/rocketmq
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_OPT_EXT
              value: '-Xms128m -Xmx128m -Xmn64m -XX:MetaspaceSize=32m -XX:MaxMetaspaceSize=32m'
          command:
            - /bin/sh
            - -c
          args:
            - echo 'brokerIP1=rocketmq.ark-dev.svc' > opt/soft/rocketmq/conf/broker.properties && /docker.sh
      #          resources:
      #            limits:
      #              memory: "1Gi"
      #              cpu: "2"
      #            requests:
      #              memory: "512Mi"
      #              cpu: "2"
      restartPolicy: Always
  selector:
    matchLabels:
      app: rocketmq
---
apiVersion: v1
kind: Service
metadata:
  name: rocketmq
  namespace: ark-dev
spec:
  selector:
    app: rocketmq
  ports:
    - port: 9876
      targetPort: 9876
      protocol: TCP
      name: namesrv
    - port: 10911
      targetPort: 10911
      protocol: TCP
      name: broker