version: '3'

services:
  zookeeper:
    image: bitnami/zookeeper
    container_name: zookeeper
    networks:
      - app-tier
    ports:
      - '2181:2181'
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
  kafka:
    image: bitnami/kafka
    container_name: kafka
    networks:
      - app-tier
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092

networks:
  app-tier:
    driver: bridge